networks:
  default:
    name: roboshop-net
    #external: true
services:
  mongodb:
    image: janardhanaau/mongodb:v1
    container_name: mongodb
  catalogue:
    image: janardhanaau/catalogue:v1
    container_name: catalogue
    environment:
      - MONGO: "true"
      - MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
    - mongodb
  redis:
    image: redis:7
    container_name: redis
  user:
    image: janardhanaau/user:v1
    container_name: user
    environment:
      - REDIS_URL: "redis://redis:6379"
      - MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - redis
    - mongodb
  cart:
    image: janardhanaau/cart:v1
    container_name: cart
    environment:
      - REDIS_HOST: "redis"
      - CATALOGUE_HOST: "catalogue"
      - CATALOGUE_PORT: "8080"
    depends_on:
    - redis
    - catalogue
  mysql:
    image: janardhanaau/mysql:v1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD: "RoboShop@1"
  shipping:
    image: janardhanaau/shipping:v1
    container _name: shipping
    environment:
      - CART_ENDPOINT: "cart:8080"
      - DB_HOST: "mysql"
    depends_on:
    - cart
    - mysql
  rabbitmq:
    image: janardhanaau/rabbitmq:v1
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"
  payment:
    image: janardhanaau/payment:v1
    container_name: payment
    environment:
      - CART_HOST: "cart"
      - CART_PORT: "8080"
      - USER_HOST: "user"
      - USER_PORT: "8080"
      - AMQP_HOST: "rabbitmq"
      - AMQP_USER: "roboshop"
      - AMQP_PASS: "roboshop123"
    depends_on:
      - cart
      - user
      - rabbitmq
  frontend:
     image: janardhanaau/frontend:v1
     container_name: frontend
     depends_on: 
       - catalogue
       - user
       - cart
       - shipping
       - payment
     ports:
       - "80:80"




    

  